// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApkBQfiwOMnt9G0i7dBxwh6ZEpVLchs_4',
    appId: '1:436314495901:web:61061e98362c905153ed74',
    messagingSenderId: '436314495901',
    projectId: 'staff-crud',
    authDomain: 'staff-crud.firebaseapp.com',
    storageBucket: 'staff-crud.firebasestorage.app',
    measurementId: 'G-C25W3618PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo-aUlqJzVoCKaBX-Ti154c7nK2o8quEE',
    appId: '1:436314495901:android:675082e1c53d116d53ed74',
    messagingSenderId: '436314495901',
    projectId: 'staff-crud',
    storageBucket: 'staff-crud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7p1KAofzJDs6nxOclzjCfjcko0Csgv10',
    appId: '1:436314495901:ios:2e1e74e31332ea9e53ed74',
    messagingSenderId: '436314495901',
    projectId: 'staff-crud',
    storageBucket: 'staff-crud.firebasestorage.app',
    iosBundleId: 'com.example.staffCrudLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7p1KAofzJDs6nxOclzjCfjcko0Csgv10',
    appId: '1:436314495901:ios:2e1e74e31332ea9e53ed74',
    messagingSenderId: '436314495901',
    projectId: 'staff-crud',
    storageBucket: 'staff-crud.firebasestorage.app',
    iosBundleId: 'com.example.staffCrudLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApkBQfiwOMnt9G0i7dBxwh6ZEpVLchs_4',
    appId: '1:436314495901:web:5e26de8838ded9db53ed74',
    messagingSenderId: '436314495901',
    projectId: 'staff-crud',
    authDomain: 'staff-crud.firebaseapp.com',
    storageBucket: 'staff-crud.firebasestorage.app',
    measurementId: 'G-4710J4RGFT',
  );
}
